// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using ScorerApp.Data;

#nullable disable

namespace ScorerApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260603150000_AddIsWhitelisted")]
    partial class AddIsWhitelisted
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder) { }
    }
}
