// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using ScorerApp.Data;

#nullable disable

namespace ScorerApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260603160000_AlignAppUserWithSharedServices")]
    partial class AlignAppUserWithSharedServices
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder) { }
    }
}
